// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqKfwylDIYSRihrLE4PtroPz4L5fXW_0',
    appId: '1:948810367379:web:c9cf1b487e1bc858602866',
    messagingSenderId: '948810367379',
    projectId: 'chatapp-79f09',
    authDomain: 'chatapp-79f09.firebaseapp.com',
    storageBucket: 'chatapp-79f09.appspot.com',
    measurementId: 'G-268H8YMF5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzh_j6LmU6AAncjLEELGuW3JSPNFewxk',
    appId: '1:948810367379:android:eb563d7e4d9c59ec602866',
    messagingSenderId: '948810367379',
    projectId: 'chatapp-79f09',
    storageBucket: 'chatapp-79f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqVNzTjAO7Rh6lpsDVsDx6LcY8OE03XU4',
    appId: '1:948810367379:ios:e266d5654347a464602866',
    messagingSenderId: '948810367379',
    projectId: 'chatapp-79f09',
    storageBucket: 'chatapp-79f09.appspot.com',
    androidClientId: '948810367379-s0for2p0qkn8ac69audd4dfobvkc466o.apps.googleusercontent.com',
    iosClientId: '948810367379-m30mf0j48cpdqkh381r70io2ic8d2hr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
